"""The SBOMs python-package-release.yml attaches to a release.

Two halves. The workflow's shape is read from the YAML: one pinned syft, the
SBOMs kept out of the PyPI upload and into the checksums, the provenance and
the release. The product is validated against the CycloneDX JSON schema: the
file syft wrote for the fixture package (committed under tests/fixtures/sbom/,
regenerated by running the workflow's own step), or, in CI, the files the
fixture-package job really produced (`SBOM_DIR`).

`cyclonedx-py` (cyclonedx-bom) has no `validate` command; the schema check is
cyclonedx-python-lib's strict JSON validator, which carries the schema.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

import yaml
from cyclonedx.schema import SchemaVersion
from cyclonedx.validation.json import JsonStrictValidator

REPO = Path(__file__).resolve().parent.parent
WORKFLOWS = REPO / ".github" / "workflows"
PACKAGE = WORKFLOWS / "python-package-release.yml"
TEXT = PACKAGE.read_text()
DOC = yaml.safe_load(TEXT)
JOBS = DOC["jobs"]
CALL = (DOC.get("on") or DOC.get(True))["workflow_call"]
SAMPLE = REPO / "tests" / "fixtures" / "sbom"


def step(job: str, fragment: str) -> dict:
    for s in JOBS[job]["steps"]:
        if fragment in (s.get("name") or "") or fragment in (s.get("uses") or ""):
            return s
    raise AssertionError(f"{job} has no step mentioning {fragment!r}")


def names(job: str) -> list[str]:
    return [s.get("name") or s.get("uses", "") for s in JOBS[job]["steps"]]


def sbom_dir() -> Path:
    return Path(os.environ.get("SBOM_DIR") or SAMPLE)


def validate(text: str):
    """Validate against the schema version the document itself declares."""
    version = json.loads(text).get("specVersion", "")
    return JsonStrictValidator(SchemaVersion.from_version(version)).validate_str(text)


# --- the workflow ----------------------------------------------------------


def test_sbom_is_on_by_default():
    assert CALL["inputs"]["sbom"]["default"] is True
    assert CALL["inputs"]["sbom"]["type"] == "boolean"


def test_syft_is_pinned_by_version_and_sha256_and_checked_before_it_runs():
    inputs = CALL["inputs"]
    assert re.fullmatch(r"\d+\.\d+\.\d+", inputs["syft-version"]["default"])
    assert re.fullmatch(r"[0-9a-f]{64}", inputs["syft-sha256"]["default"])
    env = step("build", "SBOMs with syft")["env"]
    assert env["SYFT_VERSION"] == "${{ inputs.syft-version }}"
    assert env["SYFT_SHA256"] == "${{ inputs.syft-sha256 }}"
    run = step("build", "SBOMs with syft")["run"]
    assert "anchore/syft/releases/download/v${SYFT_VERSION}/syft_${SYFT_VERSION}_linux_amd64.tar.gz" in run
    assert 'echo "${SYFT_SHA256}  ${archive}" | sha256sum -c -' in run
    assert run.index("sha256sum -c") < run.index('"$syft" scan'), "the hash is checked after syft already ran"
    assert step("build", "SBOMs with syft")["env"]["SYFT_CHECK_FOR_APP_UPDATE"] == "false"


def test_there_is_one_syft_pin_in_the_repository():
    for path in sorted(WORKFLOWS.glob("*.yml")):
        if path == PACKAGE:
            continue
        text = path.read_text()
        assert "anchore/syft/releases" not in text, f"{path.name} downloads syft with a pin of its own"
        for line in text.splitlines():
            if "syft-version" in line and not line.lstrip().startswith("#"):
                raise AssertionError(f"{path.name} sets a syft version of its own: {line.strip()}")


def test_sbom_files_stay_out_of_the_pypi_upload_and_into_the_release():
    upload = [s for s in JOBS["build"]["steps"] if s.get("with", {}).get("name") == "sbom"]
    assert len(upload) == 1 and upload[0]["if"] == "inputs.sbom"
    assert upload[0]["with"]["path"] == "${{ runner.temp }}/sbom/"
    dist = [s for s in JOBS["build"]["steps"] if s.get("with", {}).get("name") == "dist"]
    assert dist[0]["with"]["path"] == "${{ inputs.package-directory }}/dist/"
    readme = (REPO / "README.md").read_text()
    job = yaml.safe_load(re.search(r"  publish-pypi:\n(?:    .*\n|\n)+", readme).group(0))["publish-pypi"]
    pypi_downloads = [s["with"]["name"] for s in job["steps"] if "download-artifact" in s.get("uses", "")]
    assert pypi_downloads == ["dist"], "PyPI must be handed the distributions alone"
    release = JOBS["github-release"]["steps"]
    fetch = next(s for s in release if s.get("with", {}).get("name") == "sbom")
    assert fetch["if"] == "inputs.sbom" and fetch["with"]["path"] == "dist/"
    order = names("github-release")
    fetch_at = release.index(fetch)
    assert fetch_at < order.index("Checksums") < order.index("Record build provenance")
    assert order.index("Record build provenance") < order.index("Create the release, or upload to the one that exists")
    assert step("github-release", "Checksums")["run"].count("sha256sum ./*") == 1  # dist/ now holds the SBOMs
    assert step("github-release", "Record build provenance")["with"]["subject-path"] == "dist/*"


def test_the_build_refuses_an_sbom_that_names_nothing():
    run = step("build", "must name the package")["run"]
    assert step("build", "must name the package")["if"] == "inputs.sbom"
    assert "assert (want, version) in have" in run


def test_syft_needs_no_host_the_allow_list_lacks():
    hosts = CALL["inputs"]["allowed-endpoints"]["default"].split()
    for host in ("github.com:443", "release-assets.githubusercontent.com:443"):
        assert host in hosts


# --- the product -----------------------------------------------------------


def test_the_cyclonedx_file_validates_against_the_schema():
    errors = validate((sbom_dir() / "sbom.cdx.json").read_text())
    assert errors is None, f"sbom.cdx.json is not valid CycloneDX: {errors}"


def test_the_validator_is_live():
    """A schema check that cannot fail is decoration: break the file, see red."""
    doc = json.loads((sbom_dir() / "sbom.cdx.json").read_text())
    doc["bomFormat"] = "NotCycloneDX"
    assert validate(json.dumps(doc)) is not None
    doc = json.loads((sbom_dir() / "sbom.cdx.json").read_text())
    doc["components"][0]["type"] = "not-a-component-type"
    assert validate(json.dumps(doc)) is not None


def test_both_sboms_name_the_package():
    cdx = json.loads((sbom_dir() / "sbom.cdx.json").read_text())
    spdx = json.loads((sbom_dir() / "sbom.spdx.json").read_text())
    assert cdx["metadata"]["component"]["name"].replace("_", "-") == "fixture-app"
    assert any(c["name"] == "fixture-app" and c["version"] == "0.1.0" for c in cdx["components"])
    assert spdx["spdxVersion"].startswith("SPDX-")
    assert any(p["name"] == "fixture-app" and p["versionInfo"] == "0.1.0" for p in spdx["packages"])


def test_no_runner_path_survives_in_an_sbom():
    for name in ("sbom.cdx.json", "sbom.spdx.json"):
        text = (sbom_dir() / name).read_text()
        assert "/home/" not in text and "/tmp/" not in text and "sbom-stage" not in text, name
