#!/usr/bin/env python3
"""Hash-locked installs of the tools security.yml pip-installs: pip-audit and Semgrep.

A reusable workflow cannot check out its own commit, so each lock travels inside
the workflow file, as the Atheris lock does in python-fuzz.yml. The source of
truth is `.github/requirements/<tool>.in` (the one pinned version) and
`<tool>.txt` (its lock). tests/test_tool_locks.py fails when the workflow's copy
differs from the file, or the file from the `.in`.

    python scripts/tool_locks.py            copy each .txt into security.yml
    python scripts/tool_locks.py --check    write nothing; exit 1 on a difference
    python scripts/tool_locks.py --relock   resolve every .in again (needs uv and
                                            packaging, and the network), write
                                            the .txt files, then copy them in

--relock is run after editing a `.in`, or when Dependabot proposes a bump there
(Dependabot rewrites the .txt with every platform's hashes; --relock puts the
pruned lock back). Resolve in a throwaway venv on CPython 3.13:

    python3.13 -m venv /tmp/locks && /tmp/locks/bin/pip install uv packaging
    /tmp/locks/bin/python scripts/tool_locks.py --relock

The lock is pruned to what the jobs install on: ubuntu-latest is x86_64 Linux, and
the wheels kept are the manylinux x86_64 and pure-Python ones for CPython 3.10
through 3.14 (security.yml's Python is an input, 3.10 the oldest it supports).
pip-compile lists every file of every platform (Semgrep's lock alone is over a
thousand lines), which the workflow file should not carry. A package with no kept
wheel stops the script: the install runs with --only-binary, so nothing is ever
built on the runner.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQS = ROOT / ".github" / "requirements"
WORKFLOW = ROOT / ".github" / "workflows" / "security.yml"
# The step of security.yml that carries each tool's lock in its REQUIREMENTS env.
STEPS = {"pip-audit": "Install pip-audit", "semgrep": "Install Semgrep"}
PYTHONS = {f"cp3{minor}" for minor in range(10, 15)}
HEADER = (
    "# {tool}: generated by scripts/tool_locks.py from {tool}.in; do not edit.\n"
    "# Wheels for x86_64 Linux and CPython 3.10-3.14 only (see that script).\n"
)


def wanted_wheel(filename: str) -> bool:
    from packaging.utils import parse_wheel_filename

    try:
        tags = parse_wheel_filename(filename)[3]
    except Exception:
        return False
    for tag in tags:
        if tag.platform != "any" and not (tag.platform.startswith("manylinux") and tag.platform.endswith("x86_64")):
            continue
        if tag.interpreter.startswith("py3"):
            return True
        if tag.abi == "abi3" and tag.interpreter.startswith("cp3") and int(tag.interpreter[3:]) <= 10:
            return True
        if tag.interpreter in PYTHONS and tag.abi in (tag.interpreter, "none"):
            return True
    return False


def relock(tool: str) -> str:
    with tempfile.TemporaryDirectory() as tmp:
        full = Path(tmp) / "full.txt"
        command = [sys.executable, "-m", "uv", "pip", "compile", "--universal", "--python-version", "3.10"]
        command += ["--generate-hashes", "--no-annotate", "--no-header", "--quiet", "--output-file", str(full)]
        subprocess.run([*command, str(REQS / f"{tool}.in")], check=True)
        blocks = re.split(r"\n(?=\S)", full.read_text().strip())
    out = [HEADER.format(tool=tool).rstrip("\n")]
    for block in blocks:
        name, version, marker = re.match(r"([A-Za-z0-9_.\-]+)==(\S+)( ;[^\\\n]*?)? *\\", block).groups()
        if marker and re.search(r"sys_platform == '(win32|darwin|cygwin)'", marker):
            continue  # installed on no runner this workflow uses
        hashes = re.findall(r"sha256:([0-9a-f]{64})", block)
        with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=60) as response:
            files = {f["digests"]["sha256"]: f["filename"] for f in json.load(response)["urls"]}
        kept = [h for h in hashes if files.get(h, "").endswith(".whl") and wanted_wheel(files[h])]
        if not kept:
            raise SystemExit(
                f"{name}=={version} has no wheel for x86_64 Linux and CPython 3.10-3.14; the install is --only-binary"
            )
        out.append(f"{name}=={version}{marker or ''} \\\n" + " \\\n".join(f"    --hash=sha256:{h}" for h in kept))
    return "\n".join(out) + "\n"


def inline(text: str) -> str:
    for tool, step in STEPS.items():
        lock = (REQS / f"{tool}.txt").read_text()
        pattern = re.compile(
            rf"(- name: {re.escape(step)}\n(?: +[^\n]*\n)*? +REQUIREMENTS: \|\n)((?: *\n| {{12,}}[^\n]*\n)+)"
        )
        m = pattern.search(text)
        if not m:
            raise SystemExit(f"security.yml has no '{step}' step with a REQUIREMENTS block")
        body = "".join(" " * 12 + line + "\n" if line else "\n" for line in lock.rstrip("\n").split("\n"))
        text = text[: m.start(2)] + body + text[m.end(2) :]
    return text


def main(argv: list[str]) -> int:
    if "--relock" in argv:
        for tool in STEPS:
            (REQS / f"{tool}.txt").write_text(relock(tool))
    current = WORKFLOW.read_text()
    wanted = inline(current)
    if wanted == current:
        return 0
    if "--check" in argv:
        print(
            "security.yml's tool locks differ from .github/requirements/*.txt; run scripts/tool_locks.py",
            file=sys.stderr,
        )
        return 1
    WORKFLOW.write_text(wanted)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
